### ISSUE TITLE
Error on opening database

### ISSUE THREAD

**Issue by YaLTeR** [libkeepass/pykeepass#152] opened 2019-04-24 06:37 UTC
Fedora 29
pykeepass 3.0.3 (from pip3)
```python
>>> from pykeepass import PyKeePass
>>> PyKeePass('passwords.kdbx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 42, in __init__
    transformed_key=transformed_key
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 62, in read
    transformed_key=transformed_key
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 325, in parse_file
    return self.parse_stream(f, **contextkw)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 3663, in _parse
    return sc._parsereport(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/construct/core.py", line 2604, in _parse
    return self.func(context) if callable(self.func) else self.func
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/pykeepass/kdbx_parsing/kdbx4.py", line 57, in compute_transformed
    key_composite
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/pykeepass/kdbx_parsing/common.py", line 90, in aes_kdf
    keyfile=keyfile
  File "/home/YaLTeR/.local/lib/python3.7/site-packages/pykeepass/kdbx_parsing/common.py", line 107, in compute_key_composite
    password_composite = hashlib.sha256(password.encode('utf-8')).digest()
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by Evidlo** [comment] 2019-04-24 06:53
How did you manage to generate a database with no password or keyfile set?

**Comment by YaLTeR** [comment] 2019-04-24 06:56
Uhh, it's my normal database that I use with KeePass and KeePassXC.

**Comment by Evidlo** [comment] 2019-04-24 07:00
How did you generate it?  Keepass and KeepassXC won't let me create a database without checking off `password` or `keyfile`.  Opening is a different story, though.

**Comment by YaLTeR** [comment] 2019-04-24 07:16
The database does have a password. The exact same error occurs when I try opening it with `PyKeePass('passwords.kdbx', password='my_pass')`. I generated it with KeePass long ago.

**Comment by Evidlo** [comment] 2019-04-24 07:24
Can you test this with a freshly generated database from KeepassXC?

**Comment by YaLTeR** [comment] 2019-04-24 07:28
Seems to work on a fresh database from KeePassXC.

**Comment by Evidlo** [comment] 2019-04-24 23:36
Would you be willing to mail me a copy of your database with all the entries/groups removed?  I need to dig  down into the weeds to figure out what's happening.

**Comment by YaLTeR** [comment] 2019-04-25 06:45
I mailed it to the e-mail address listed on your GitHub profile.

**Comment by freundTech** [comment] 2019-05-03 08:06
I'm getting the same error when trying to open my database.
Error used to not occure with the database, so it is probably caused by another program changing something about the database (In my case either keepassXC or keepassDX, which I both use with the database. Both can still open the database).

**Comment by YaLTeR** [comment] 2019-05-03 08:08
FWIW apart from KeepassXC I use the database with Keepass2Android on my phone.

**Comment by reflog** [comment] 2019-05-03 09:48
same here

**Comment by Evidlo** [comment] 2019-05-16 16:16
@YaLTeR I can't open that sample database you sent me in either KeePass or KeePassXC.

**Comment by Evidlo** [comment] 2019-05-16 16:28
The temporary fix is to switch from AESKDF to argon2:

In KeepassXC, `Database > Database Settings > Encryption > Key Derivation Function`.

**Comment by Evidlo** [comment] 2019-05-16 17:47
Try this branch and tell me if it works with AESKDF: https://github.com/Evidlo/pykeepass/tree/aeskdf_fix

You're probably going to want to turn the rounds down.  AES key derivation is implemented pretty inefficiently in the library were using, so 116341992 is going to take forever.

**Comment by YaLTeR** [comment] 2019-05-17 20:15
That branch seems to open my database fine.

**Comment by YaLTeR** [comment] 2019-07-11 20:29
So... What happened to this? The branch works fine for me.

**Comment by Evidlo** [comment] 2019-07-13 19:36
I'm waiting for @pschmitt to merge two other PR's before making another PR.

**Comment by Evidlo** [comment] 2019-09-12 01:53
Should be fixed by https://github.com/libkeepass/pykeepass/commit/da88c0d1e952e3e4f7d2a8822b05232241dd49d9

**Closed by Evidlo** 2019-09-12 01:53 UTC
