### ISSUE TITLE
'NoneType' object has no attribute 'payload'

### ISSUE THREAD

**Issue by smalhot9464** [libkeepass/pykeepass#265] opened 2021-06-28 19:39 UTC
from pykeepass import PyKeePass

try:
        kp = PyKeePass("newdb.kdb", password="qwerty@123")
except:
        print("Got exception")

lstEntry = kp.find_entries_by_notes(".*testing.*",regex=True)
print(lstEntry)

Traceback (most recent call last):
  File "keeps.py", line 8, in <module>
    lstEntry = kp.find_entries_by_notes(".*testing.*",regex=True)
  File "/home/oracle/env/lib64/python3.6/site-packages/pykeepass/pykeepass.py", line 564, in find_entries_by_notes
    first=first
  File "/home/oracle/env/lib64/python3.6/site-packages/pykeepass/pykeepass.py", line 508, in find_entries
    res = self._find(prefix, entry_xp, path=path, tree=group, **kwargs)
  File "/home/oracle/env/lib64/python3.6/site-packages/pykeepass/pykeepass.py", line 362, in _find
    **kwargs
  File "/home/oracle/env/lib64/python3.6/site-packages/pykeepass/pykeepass.py", line 279, in _xpath
    tree = self.tree
  File "/home/oracle/env/lib64/python3.6/site-packages/pykeepass/pykeepass.py", line 200, in tree
    return self.kdbx.body.payload.xml
AttributeError: 'NoneType' object has no attribute 'payload'

**Comment by Evidlo** [comment] 2021-07-04 04:06
I'm not able to reproduce this.  What version of pykeepass are you using?

``` python
>>> from pykeepass import PyKeePass; kp = PyKeePass('tes
...: t3.kdbx', 'password', 'test3.key')

>>> kp.find_entries(notes='.*note.*', regex=True)
Out[8]: 
[Entry: "root_entry (foobar_user)",
 Entry: "foobar_group/group_entry (foobar_user)"]
```

Also `find_entries_by_notes` is deprecated.  Use `find_entries(notes=".testing.", regex=True)`

**Comment by CatalinSoare** [comment] 2021-12-13 06:27
Hello,
I am also getting this issue:

Here is some sample code that throws the same error (using version 4.0.1):
```
from pykeepass import PyKeePass
import getpass

filename = "db.kdbx"

try:
    password
except NameError:
    print("'password' is not defined")
    password = getpass.getpass("Please enter the password for this keepass DB: ")

            # load database
kp = PyKeePass(filename, password=password)
for entry in kp.entries:
    print(entry)
```

My error:

```
>>> for entry in kp.entries:
...     print(entry)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 224, in entries
    return self._xpath('//Entry', cast=True)
  File "/home/user/.local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 279, in _xpath
    tree = self.tree
  File "/home/user/.local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 200, in tree
    return self.kdbx.body.payload.xml
AttributeError: 'NoneType' object has no attribute 'payload'
```

**Comment by Evidlo** [comment] 2021-12-15 22:16
Can you provide an example database?

**Comment by rtl19** [comment] 2022-07-01 15:21
@Evidlo , while I didn't open this original issue, I'm seeing the same error when I open a non keepass file.  In other words, If I give it a regular xml file (for example), the keepass library will return a keepass object without any errors.  Then, if you attempt to use any of the standard functions of keepass, you'll get this payload error.  It doesn't matter if I specify a password for the file or not.  It returns success until you try to use the keepass object.

**Comment by Evidlo** [comment] 2022-07-05 15:16
This should be fixed with https://github.com/libkeepass/pykeepass/commit/ac35a16c813e3e8f4e4fb0db7cb5e35f7b01fcfb

**Closed** 2022-07-05 15:19 UTC
