### ISSUE TITLE
the attribute 'entries' won't return all of records?

### ISSUE THREAD

**Issue by scruel** [libkeepass/pykeepass#193] opened 2020-03-29 17:00 UTC
It seems that the attribute 'entries' won't return all records in the kepass database, the following code in the image will expose this issue.

![图片](https://user-images.githubusercontent.com/16933298/77855183-6d368c00-7221-11ea-9edc-302d6279b7aa.png)

**Comment by Evidlo** [comment] 2020-03-30 01:31
Can you reproduce this on a test database without blurring out your query?

**Comment by scruel** [comment] 2020-03-30 10:01
Reproduce without blurring out my query is not possible, cause this problem seems only exists in the database which have thousands records...

**Comment by pschmitt** [comment] 2020-03-30 12:01
This won't make it easy to debug.
Do your entries contain non-ASCII/UTF-8 chars? You seem to be located in Asia.

**Comment by scruel** [comment] 2020-04-04 10:03
There are Chinese characters in the customs properties, but many other entries which can be retrieved by 'entries' also has Chinese characters...
Meanwhile, using the method `kp1.find_entries_by_username('.*', regex=True)` will return the whole records in the database.

**Comment by scruel** [comment] 2020-04-04 10:09
I can't give you the whole database for debugging, but maybe you can tell me how to get the useful logs, then I can reproduce it and send the log file to you.

**Comment by Evidlo** [comment] 2020-04-26 23:10
What is the username and title for one of the entries which *doesn't* appear with `entries`, but *does* appear with `find_entries_by_username`?

**Comment by scruel** [comment] 2020-05-01 19:07
> 
> 
> What is the username and title for one of the entries which _doesn't_ appear with `entries`, but _does_ appear with `find_entries_by_username`?

Title contains the Chinese characters, username is an email.

**Comment by Evidlo** [comment] 2020-05-01 20:07
Can you paste those fields please?  I need to reproduce this issue if it's going to be fixed.

> this problem seems only exists in the database which have thousands records...

Are you saying if you have a database with only one of these Chinese entries, `kp.entries` works?

**Comment by scruel** [comment] 2020-05-01 22:29
Wired thing is that when I try to reproduce this issue with the same code again(records of the database already changed), the result comes to true...
I realized that I haven't use the `save` function for a while, so I run `save` in current database and then check the result multiple times, but I got nothing changes and the results are always true...

I will close this issue because even I can't reproduce it now...
And If this issue remain in the future, I will reopen it and post with necessary information for debugging.
Even though I do promise this issue truly happened, but I have to say sorry for forgetting keep the relevant files.

**Comment by scruel** [comment] 2020-05-13 20:52
Well, this time, you can reproduce this issue via the following kdbx file.

File:
https://lanzous.com/iclfpud

Code:
```
kp = PyKeePass(r"D:\temp1.kdbx", password="1")
print(len(kp.entries))
print(len(kp.find_entries_by_username(".*", regex=True)))
```

Result:
```
1
2
```

**Comment by Evidlo** [comment] 2020-05-19 15:42
This should be fixed with https://github.com/libkeepass/pykeepass/commit/18e105a395f73d4b0d623d1d7f6103de176e87a6.

The problem was happening because your entry didn't have a title tag.  What did you use to create this entry?

**Closed** 2020-05-29 03:52 UTC
