### ISSUE TITLE
Corrupted database: Saving with a non existent keyfile

### ISSUE THREAD

**Issue by A6GibKm** [libkeepass/pykeepass#223] opened 2020-12-28 16:04 UTC
In password safe, after opening a keyfile/composite database, if one renames the keyfile, introduces some change and then proceeds to save (a call to save() in pykeepass) the safe could result corrupted in certain scenarios, which would result of a crash when opening it.

Sometimes it would be corrupted and sometimes it wont, making me think that this block

```
            try:
                self.db.save()
                logging.debug("Saved database")
            except Exception:
                logging.error("Error occurred while saving database")
```

does not accomplish its purpose as some part of db.save()  happens before checking if the keyfile actually exists.

See https://gitlab.gnome.org/World/PasswordSafe/-/merge_requests/434 and its corresponding issue.

**Comment by Evidlo** [comment] 2021-01-05 21:25
I can confirm this error.  Test code below:

``` python
import shutil
import os
from pykeepass import PyKeePass

# setup
shutil.copy('test4.kdbx', 'test4_issue223.kdbx')
shutil.copy('test4.key', 'test4_issue223.key')

# open database and make change
kp = PyKeePass('test4_issue223.kdbx', 'password', 'test4_issue223.key')
kp.entries[0].title = 'newtitle'

# move keyfile
new_keyfile = 'test4_issue223_new.key'
if os.path.exists(new_keyfile):
    os.remove(new_keyfile)
shutil.move('test4_issue223.key', new_keyfile)

# save
try:
    kp.save()
except Exception as e:
    print('Got exception while saving:', type(e))

# open database with new keyfile
try:
    kp = PyKeePass('test4_issue223.kdbx', 'password', new_keyfile)
    print(kp.root_entry)
except Exception as e:
    print('Got exception while opening:', e)
```

**Comment by Evidlo** [comment] 2021-01-08 02:42
See https://github.com/libkeepass/pykeepass/pull/229 and https://github.com/libkeepass/pykeepass/pull/229 and let me know what you think.

I'm leaning towards the BytesIO solution here.

**Comment by pschmitt** [comment] 2021-01-08 06:27
+1 for #230

**Comment by Evidlo** [comment] 2021-01-09 22:55
I've learned that #229 is safer because `os.replace` is an atomic operation whereas reading out of BytesIO is not.

**Comment by A6GibKm** [comment] 2022-03-14 07:47
I tested both approaches and I could not reproduce the issue in either. While being atomic is desirable, doing extra I/O is not and I am leaning towards the bytesIO solution, maybe there is an atomic way to use a copy in memory?.

**Comment by A6GibKm** [comment] 2022-03-16 19:36
I implemented locally the bytesIO method in https://gitlab.gnome.org/World/secrets/-/merge_requests/663, since Gio operations are atomic and async it works very well.

**Comment by Evidlo** [comment] 2022-03-18 04:46
#229 (temp file using tempfile module) was merged

**Closed by Evidlo** 2022-03-18 04:46 UTC
